//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bcad_SiteInfo
    {
        public long siteID { get; set; }
        public Nullable<int> siteTitleID { get; set; }
        public string thetaValue { get; set; }
        public string ElevCraneDistance { get; set; }
    }
}
