//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bcad_CraneData
    {
        public long CraneDataID { get; set; }
        public Nullable<long> CraneID { get; set; }
        public string OR_sp { get; set; }
        public string FP_radius { get; set; }
        public string FP_Height { get; set; }
        public string Boom_length { get; set; }
        public string Boom_depth { get; set; }
        public string Boom_width { get; set; }
        public string Boom_Ext { get; set; }
        public string Jib_length { get; set; }
        public string Offset { get; set; }
    }
}
