//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorEmailDescription
    {
        public int EmaildesID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public string EmailSubject { get; set; }
        public string EmailDescription { get; set; }
    }
}
