//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorHistory
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> Aging { get; set; }
        public System.DateTime AgingUpdateDate { get; set; }
        public int Userid { get; set; }
    }
}
