//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string CompanyNo { get; set; }
        public string Country { get; set; }
        public string FedExNUM { get; set; }
        public string IBMNUM { get; set; }
        public string AirborneExpNUM { get; set; }
        public string DotInsuranceExp { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Age0Action { get; set; }
        public Nullable<int> Age15Action { get; set; }
        public Nullable<int> Age30Action { get; set; }
        public Nullable<int> Age45Action { get; set; }
        public Nullable<int> Age60Action { get; set; }
        public Nullable<int> Age75Action { get; set; }
        public Nullable<int> Age90Action { get; set; }
        public Nullable<int> Age105Action { get; set; }
        public Nullable<int> Aging { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public string DueInvoiceNo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public Nullable<bool> IsChange { get; set; }
        public Nullable<bool> IsNewRecord { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<bool> DBadClient { get; set; }
        public Nullable<bool> IsCreditPass { get; set; }
        public Nullable<System.DateTime> CreditPassDate { get; set; }
        public Nullable<int> TableVersionId { get; set; }
        public string OfficePhone { get; set; }
        public string OfficeFax { get; set; }
        public string TypicalInvoiceType { get; set; }
        public Nullable<decimal> ServRate { get; set; }
    }
}
