//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRVTimeInvoice
    {
        public long CRVTimeInvoiceID { get; set; }
        public Nullable<long> JobTrackDetailID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Time { get; set; }
        public string Description { get; set; }
        public string Rate { get; set; }
        public string Name { get; set; }
        public string JobTrackSubName { get; set; }
        public Nullable<int> TimeSheetID { get; set; }
    }
}
