//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetails_Depre
    {
        public long Id { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Designation { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public string UserType { get; set; }
        public string BillableRate { get; set; }
        public Nullable<bool> ActiveUser { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> MasterItemId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
