//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportTimeSheetData
    {
        public long ID { get; set; }
        public string JobNumber { get; set; }
        public string PM { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Duration { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<double> ChangeHours { get; set; }
    }
}
