//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAction
    {
        public long ActionID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string InvoiceNo { get; set; }
        public string ActionName { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
    }
}
