//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTrackInvoiceRateDetail
    {
        public decimal InvoiceRptID { get; set; }
        public Nullable<int> TrackSubID { get; set; }
        public string JobTrackSubName { get; set; }
        public Nullable<decimal> JobTrackDetailID { get; set; }
        public Nullable<decimal> Hrs { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string byname { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Clienttext { get; set; }
        public Nullable<int> JobTrackingID { get; set; }
    }
}
