//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptInvoiceTime
    {
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Jobdescription { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<double> Time { get; set; }
        public decimal JobTrackDetailID { get; set; }
        public string JobNumber { get; set; }
        public string PONo { get; set; }
        public Nullable<decimal> PaymentCr { get; set; }
        public Nullable<decimal> BalanceDue { get; set; }
        public Nullable<int> Aging { get; set; }
        public Nullable<decimal> OpeningBal { get; set; }
        public string Rate { get; set; }
        public string Clienttext { get; set; }
        public string Name { get; set; }
        public string JobTrackSubName { get; set; }
    }
}
