//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBFormInfo
    {
        public int JobID { get; set; }
        public Nullable<int> JobListID { get; set; }
        public string JobNumber { get; set; }
        public Nullable<int> Applicant { get; set; }
        public string JobSiteBlock { get; set; }
        public string JobSiteLot { get; set; }
        public string JobSiteCNNum { get; set; }
        public string JobSiteHouseNum { get; set; }
        public string JobSiteStreet { get; set; }
        public string JobSiteBorough { get; set; }
        public string JobSiteState { get; set; }
        public Nullable<int> Crane1CD { get; set; }
        public Nullable<int> Crane2CD { get; set; }
        public Nullable<int> Crane3CD { get; set; }
        public Nullable<int> Crane4CD { get; set; }
        public Nullable<int> Crane5CD { get; set; }
        public Nullable<int> Crane6CD { get; set; }
        public Nullable<int> CraneUser { get; set; }
        public string CraneUserInfo { get; set; }
        public string CraneUserTitle { get; set; }
        public string WorkPlatformManufacturer { get; set; }
        public string WorkPlatformModel { get; set; }
        public string WorkPlatformSuperName { get; set; }
        public string WorkPlatformSuperPhone { get; set; }
        public string WorkPlatformSuperFax { get; set; }
        public string WorkPlatformSuperAddr { get; set; }
        public string WorkPlatformSuperCity { get; set; }
        public string WorkPlatformSuperState { get; set; }
        public string WorkPlatformSuperZip { get; set; }
        public bool FirstVariance { get; set; }
        public string BIN { get; set; }
        public string CBNum { get; set; }
        public string AptorCondoNum { get; set; }
        public string SpecialPlaceName { get; set; }
        public Nullable<int> SubName { get; set; }
        public string SubInfo { get; set; }
        public bool ResidenceWithin200ft { get; set; }
        public string DatesofVariance { get; set; }
        public string DaysofVariance { get; set; }
        public string TimeofVarianceFrom { get; set; }
        public string TimeofVarianceTo { get; set; }
        public string VarianceWorkDescription { get; set; }
        public string ReasonforVariance { get; set; }
        public Nullable<int> SiteArchitect { get; set; }
        public Nullable<int> CommunityBoardID { get; set; }
        public string SiteNumofStories { get; set; }
        public bool SiteOccupancy { get; set; }
        public string OccupancyType { get; set; }
        public string SiteNumofApts { get; set; }
        public string SiteNumofAptsCurrent { get; set; }
        public string SiteNumofAptsProposed { get; set; }
        public string SiteOwner { get; set; }
        public string SiteOwnerAddress { get; set; }
        public string SiteOwnerStreet { get; set; }
        public string SiteOwnerCity { get; set; }
        public string SiteOwnerState { get; set; }
        public string SiteOwnerZip { get; set; }
        public string WorkProposed { get; set; }
        public string Architect2 { get; set; }
        public string Architect2fullAddress { get; set; }
        public Nullable<bool> IsChange { get; set; }
        public Nullable<bool> IsNewRecord { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string PDFType { get; set; }
    }
}
