//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VBNetApplicantInfo
    {
        public int ApplicantID { get; set; }
        public string ApplicantFirstName { get; set; }
        public string ApplicantLastName { get; set; }
        public string ApplicantMidName { get; set; }
        public string ApplicantBusinessName { get; set; }
        public string ApplicantBusinessAddress { get; set; }
        public string ApplicantBusinessCity { get; set; }
        public string ApplicantBusinessState { get; set; }
        public string ApplicantBusinessZip { get; set; }
        public string ApplicantTitle { get; set; }
        public string ApplicantLicense { get; set; }
        public string ApplicantPhone { get; set; }
        public string Applicantfax { get; set; }
        public Nullable<bool> IsChange { get; set; }
        public Nullable<bool> IsNewRecord { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    }
}
