//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Temp
    {
        public string InvoiceNo { get; set; }
        public string InvoiceDate { get; set; }
        public string Jobdescription { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public decimal JobTrackDetailID { get; set; }
        public string JobNumber { get; set; }
        public string PONo { get; set; }
        public Nullable<decimal> PaymentCr { get; set; }
        public string Date { get; set; }
        public Nullable<double> Hrs { get; set; }
        public string Rate { get; set; }
        public string JobTrackSubName { get; set; }
        public string byname { get; set; }
        public string Amount { get; set; }
        public string Clienttext { get; set; }
        public Nullable<double> Expenses { get; set; }
        public string ReportType { get; set; }
    }
}
