//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PandingList
    {
        public int JobTrackingID { get; set; }
        public Nullable<int> JobListID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> NeedDate { get; set; }
        public Nullable<System.DateTime> Obtained { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Submitted { get; set; }
        public string BillState { get; set; }
        public string TaskHandler { get; set; }
        public string Comments { get; set; }
        public string FinalAction { get; set; }
        public Nullable<int> TrackSubID { get; set; }
        public string TrackName { get; set; }
        public string TrackSubName { get; set; }
    }
}
