//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSetting
    {
        public int AppID { get; set; }
        public Nullable<System.DateTime> CompareDate { get; set; }
        public string CompareSchedule { get; set; }
        public Nullable<bool> CompareActiveTimer { get; set; }
        public Nullable<bool> ActiveWebUpload { get; set; }
        public string NewVersion { get; set; }
        public string ApprovedVersion { get; set; }
    }
}
