//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bcad_Capacity
    {
        public int ID { get; set; }
        public Nullable<int> CraneConfigID { get; set; }
        public Nullable<int> RadiusID { get; set; }
        public Nullable<double> Radius { get; set; }
        public Nullable<double> Capacity { get; set; }
    }
}
