//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawingLog
    {
        public int DrawingLogID { get; set; }
        public Nullable<int> JobListID { get; set; }
        public string JobNumber { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string StorageLocation { get; set; }
        public Nullable<System.DateTime> LastUsed { get; set; }
        public string AKA { get; set; }
    }
}
