//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailJobPendingList
    {
        public string JobNumber { get; set; }
        public string Address { get; set; }
        public string Contacts { get; set; }
        public string EmailAddress { get; set; }
        public string Track { get; set; }
        public string TrackSub { get; set; }
        public string Comments { get; set; }
        public int JobListID { get; set; }
    }
}
