//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Expences
    {
        public long TimeSheetExpencesID { get; set; }
        public Nullable<long> JobListID { get; set; }
        public Nullable<long> EmployeeDetailsId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TrackSubID { get; set; }
        public string TrackSubName { get; set; }
        public Nullable<double> Expences { get; set; }
        public string Description { get; set; }
        public string status { get; set; }
        public string BillState { get; set; }
        public string MassStatusChangeBox { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Comment { get; set; }
        public string AdminStatus { get; set; }
    }
}
