//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_MasterItem
    {
        public long TS_MasterItemId { get; set; }
        public string ItemName { get; set; }
        public string Value { get; set; }
        public string UserType { get; set; }
    }
}
